// flow-typed signature: 60050cf215643b2ffe708e5bb12ffdbf
// flow-typed version: <<STUB>>/asset-rev_v^0.2.0/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'asset-rev'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'asset-rev' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'asset-rev/bin/rev' {
  declare module.exports: any;
}

// Filename aliases
declare module 'asset-rev/bin/rev.js' {
  declare module.exports: $Exports<'asset-rev/bin/rev'>;
}
declare module 'asset-rev/index' {
  declare module.exports: $Exports<'asset-rev'>;
}
declare module 'asset-rev/index.js' {
  declare module.exports: $Exports<'asset-rev'>;
}
