// flow-typed signature: 0731020b4599bdebb227c122d8128745
// flow-typed version: <<STUB>>/confetti-js_v^0.0.18/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'confetti-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'confetti-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'confetti-js/dist/index.es' {
  declare module.exports: any;
}

declare module 'confetti-js/dist' {
  declare module.exports: any;
}

declare module 'confetti-js/dist/index.min' {
  declare module.exports: any;
}

declare module 'confetti-js/rollup.config' {
  declare module.exports: any;
}

declare module 'confetti-js/site/site' {
  declare module.exports: any;
}

declare module 'confetti-js/src/confetti' {
  declare module.exports: any;
}

// Filename aliases
declare module 'confetti-js/dist/index.es.js' {
  declare module.exports: $Exports<'confetti-js/dist/index.es'>;
}
declare module 'confetti-js/dist/index' {
  declare module.exports: $Exports<'confetti-js/dist'>;
}
declare module 'confetti-js/dist/index.js' {
  declare module.exports: $Exports<'confetti-js/dist'>;
}
declare module 'confetti-js/dist/index.min.js' {
  declare module.exports: $Exports<'confetti-js/dist/index.min'>;
}
declare module 'confetti-js/rollup.config.js' {
  declare module.exports: $Exports<'confetti-js/rollup.config'>;
}
declare module 'confetti-js/site/site.js' {
  declare module.exports: $Exports<'confetti-js/site/site'>;
}
declare module 'confetti-js/src/confetti.js' {
  declare module.exports: $Exports<'confetti-js/src/confetti'>;
}
